name: Deploy version

on:
  push:
    tags: v*.*.*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "11.0"

    - name: Verify Clang
      run: |
        clang --version
        wasm-ld --version

    - name: npm install
      run: |
        npm ci
      env:
        CI: true

    - name: Build JS
      run: |
        npm run build

    - name: Build WASM
      run: |
        make lib/dsl.wasm

    - name: Publish
      uses: matthewp/cdn-spooky-deploy-action@v3.beta.2
      with:
        key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        pkg: 'untitled-dsl-project'
        source: 'lib'